# Production environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_prod
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      TRUSTED_HOSTS: '^(.+\.)?cinephoria\.me$'
      CORS_ALLOW_ORIGIN: '^https://cinephoria\.me$'

  pwa:
    build:
      context: ./pwa
      target: prod
    environment:
      HOST: 0.0.0.0
      NEXT_PUBLIC_IS_PRODUCTION: true


  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}