lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl: 3600

    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization

    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password

when@test:
    lexik_jwt_authentication:
        secret_key: '%kernel.project_dir%/config/jwt/private-test.pem'
        public_key: '%kernel.project_dir%/config/jwt/public-test.pem'
