'use client'
import "./ui/globals.css";
import React, {useState} from "react";
import {QueryClient} from "@tanstack/query-core";
import {QueryClientProvider} from "@tanstack/react-query";
import {UserProvider} from "@/app/context/UserContext";

/*export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};*/

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const [queryClient] = useState(() => new QueryClient());

    return (
        <QueryClientProvider client={queryClient}>
            <UserProvider>
                <html lang="fr">
                <body>
                {children}
                </body>
                </html>
            </UserProvider>
        </QueryClientProvider>
    );
}
