name: Release
permissions:
  contents: write 
  pull-requests: write

on:
  workflow_run:
    workflows: [ "CI Tauri" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: 'ID du run CI à utiliser pour télécharger les artifacts'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Show workflow_run info
        run: |
          echo "workflow_run.id       = ${{ github.event.workflow_run.id }}"
          echo "workflow_run.head_sha = ${{ github.event.workflow_run.head_sha }}"
          echo "workflow_run.head_branch = ${{ github.event.workflow_run.head_branch }}"
          echo "run_id (current workflow) = ${{ github.run_id }}"

      - name: Download Tauri build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: tauri-binaries-${{ matrix.platform }}
          path: desktop_app/src-tauri/target/release/
          repository: Aurelie-feyzin/cinephoria
          run-id: ${{ github.event.workflow_run.id || github.event.inputs.ci_run_id  }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List downloaded files
        run: ls -lh desktop_app/src-tauri/target/release

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: 'desktop_app'
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
